# Generated by Django 3.1 on 2020-11-15 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comprasenc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='api.comprasenc')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Compras',
            },
        ),
    ]
